// sitemap.ts - Dynamic Sitemap Generation
// Path: src/app/sitemap.ts

import { MetadataRoute } from "next";

// All Melbourne suburbs for dynamic suburb pages (matches filesystem directories)
const MELBOURNE_SUBURBS = [
  "abbotsford",
  "airport-west",
  "albert-park",
  "albion",
  "altona",
  "altona-meadows",
  "ardeer",
  "armadale",
  "ascot-vale",
  "aspendale",
  "aspendale-gardens",
  "ashwood",
  "attwood",
  "avonsleigh",
  "badger-creek",
  "balaclava",
  "balwyn",
  "balwyn-north",
  "bangholme",
  "baxter",
  "bayswater",
  "beaconsfield",
  "beaumaris",
  "belgrave",
  "bentleigh",
  "bentleigh-east",
  "berwick",
  "bittern",
  "black-rock",
  "blackburn-north",
  "blairgowrie",
  "boneo",
  "boronia",
  "botanic-ridge",
  "box-hill",
  "briar-hill",
  "brighton",
  "brighton-east",
  "broadmeadows",
  "brunswick",
  "brunswick-east",
  "brunswick-west",
  "bulleen",
  "bundoora",
  "burnley",
  "burwood-3125",
  "burwood-chadstone",
  "burwood-east",
  "camberwell",
  "campbellfield",
  "canterbury",
  "carlton",
  "carlton-north",
  "carnegie",
  "caulfield",
  "caulfield-east",
  "caulfield-north",
  "caulfield-south",
  "chadstone",
  "chelsea",
  "chelsea-heights",
  "cheltenham",
  "chirnside-park",
  "clayton",
  "clayton-south",
  "clifton-hill",
  "clyde",
  "clyde-north",
  "coburg",
  "coburg-north",
  "collingwood",
  "craigieburn",
  "cremorne",
  "croydon",
  "croydon-hills",
  "croydon-north",
  "croydon-south",
  "dallas",
  "dandenong",
  "dandenong-north",
  "dandenong-south",
  "deer-park",
  "delahey",
  "docklands",
  "doncaster",
  "doncaster-east",
  "donvale",
  "doveton",
  "eaglehawk",
  "east-melbourne",
  "elsternwick",
  "eltham",
  "elwood",
  "epping",
  "essendon",
  "essendon-fields",
  "fawkner",
  "ferntree-gully",
  "fitzroy",
  "fitzroy-north",
  "flemington",
  "footscray",
  "frankston",
  "frankston-north",
  "frankston-south",
  "gembrook",
  "glen-huntly",
  "glen-waverley",
  "greensborough",
  "hadfield",
  "hallam",
  "hampton",
  "hampton-park",
  "hawthorn",
  "hawthorn-east",
  "heatherton",
  "heidelberg",
  "heidelberg-west",
  "highett",
  "hillside",
  "hoppers-crossing",
  "ivanhoe",
  "keilor",
  "keilor-downs",
  "keilor-lodge",
  "kensington",
  "kew",
  "kew-east",
  "keysborough",
  "kings-park",
  "knoxfield",
  "lakes-entrance",
  "lalor",
  "langwarrin",
  "lara",
  "laverton",
  "laverton-north",
  "lilydale",
  "little-river",
  "macleod",
  "maidstone",
  "malvern",
  "malvern-east",
  "maribyrnong",
  "maroondah",
  "melbourne",
  "melbourne-airport",
  "melbourne-cbd",
  "melbourne-east",
  "melbourne-south",
  "melton",
  "melton-south",
  "mernda",
  "middle-park",
  "mill-park",
  "mitcham",
  "moonee-ponds",
  "moorabbin",
  "mordialloc",
  "mornington",
  "mount-eliza",
  "mount-evelyn",
  "mount-waverley",
  "mulgrave",
  "narre-warren",
  "narre-warren-north",
  "narre-warren-south",
  "newport",
  "niddrie",
  "north-melbourne",
  "northcote",
  "nunawading",
  "oakleigh",
  "oakleigh-south",
  "ormond",
  "pakenham",
  "pakenham-south",
  "pakenham-upper",
  "parkdale",
  "pascoe-vale",
  "pascoe-vale-south",
  "point-cook",
  "point-leo",
  "port-melbourne",
  "portsea",
  "prahran",
  "preston",
  "reservoir",
  "richmond",
  "ringwood",
  "ringwood-east",
  "ringwood-north",
  "rivervale",
  "rosanna",
  "rowville",
  "sandringham",
  "scoresby",
  "seaford",
  "skye",
  "somerville",
  "south-melbourne",
  "south-morang",
  "south-yarra",
  "southbank",
  "spotswood",
  "springvale",
  "springvale-south",
  "st-albans",
  "st-kilda",
  "st-kilda-east",
  "strathmore",
  "sunshine",
  "sunshine-north",
  "sunshine-west",
  "surrey-hills",
  "sydenham",
  "tarneit",
  "templestowe",
  "templestowe-lower",
  "thomastown",
  "thornbury",
  "tooradin",
  "toorak",
  "truemans",
  "truganina",
  "tullamarine",
  "tyabb",
  "upper-ferntree-gully",
  "vermont",
  "vermont-south",
  "wantirna",
  "wantirna-south",
  "werribee",
  "werribee-south",
  "west-footscray",
  "west-melbourne",
  "wheelers-hill",
  "williamstown",
  "windsor",
  "wollert",
  "yallambie",
  "yarra-glen",
  "yarra-junction",
  "yarrambat",
  "yarraville",
  "yellingbo",
  "yering",
];

// Services for service pages
const SERVICES = [
  { path: "/gas-ducted-heating", name: "Gas Ducted Heating" },
  { path: "/hydronic-heating", name: "Hydronic Heating" },
  {
    path: "/split-system-air-conditioning",
    name: "Split System Air Conditioning",
  },
  { path: "/emergency-services", name: "Emergency Services" },
  { path: "/hot-water-repairs", name: "Hot Water Repairs Melbourne" },
  { path: "/carbon-monoxide-testing", name: "Carbon Monoxide Testing Melbourne" },
];

// Service sub-pages (individual service detail pages)
const SERVICE_SUB_PAGES = [
  "/gas-ducted-heating/emergency-gas-ducted-repair-melbourne",
  "/gas-ducted-heating/gas-ducted-installation-melbourne",
  "/gas-ducted-heating/gas-heater-repair-melbourne",
  "/gas-ducted-heating/gas-heater-replacement-maintenance-melbourne",
  "/gas-ducted-heating/gas-heater-service-and-maintenance-melbourne",
  "/hydronic-heating/emergency-hydronic-repair-melbourne",
  "/hydronic-heating/hydronic-heater-installation-melbourne",
  "/hydronic-heating/hydronic-heater-repair-melbourne",
  "/hydronic-heating/hydronic-heater-service-maintainance-melbourne",
  "/hydronic-heating/underfloor-slab-heating-repair-melbourne",
  "/split-system-air-conditioning/ac-deep-cleaning-sanitization-melbourne",
  "/split-system-air-conditioning/emergency-split-system-repair-melbourne",
  "/split-system-air-conditioning/multi-head-system-service-melbourne",
  "/split-system-air-conditioning/split-system-installation-melbourne",
  "/split-system-air-conditioning/split-system-repair-melbourne",
  "/emergency-services/ac-breakdown-rescue-melbourne",
  "/emergency-services/emergency-gas-ducted-repair-melbourne",
  "/emergency-services/emergency-gas-leak-repair-melbourne",
  "/emergency-services/emergency-hydronic-repair-melbourne",
  "/emergency-services/emergency-split-system-repair-melbourne",
  "/emergency-services/hydronic-leak-repair",
];

// Self-care brand pages matching filesystem directories (no bonaire)
const SELF_CARE_BRANDS = [
  "actronair",
  "braemar",
  "breezair",
  "brivis",
  "carrier",
  "celair",
  "fujitsu",
  "haier",
  "hitachi",
  "kaden",
  "lg",
  "mitsubishi-electric",
  "panasonic",
  "rinnai",
  "samsung",
  "sharp",
  "toshiba",
  "vulcan",
  "york",
];

// All brand pages matching filesystem directories
const BRANDS = [
  "actronair",
  "bonaire",
  "braemar",
  "breezair",
  "brivis",
  "carrier",
  "celair",
  "fujitsu",
  "haier",
  "hitachi",
  "kaden",
  "lg",
  "mitsubishi-electric",
  "panasonic",
  "rinnai",
  "samsung",
  "sharp",
  "toshiba",
  "vulcan",
  "york",
];

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://heaterservicemelbourne.com.au";

  // Static pages
  const staticPages: MetadataRoute.Sitemap = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/contact`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/services`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${baseUrl}/service-areas`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${baseUrl}/brands`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: `${baseUrl}/blog`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.7,
    },
  ];

  // Service pages
  const servicePages: MetadataRoute.Sitemap = SERVICES.map((service) => ({
    url: `${baseUrl}${service.path}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.9,
  }));

  // Dynamic suburb pages under /service-areas/{suburb}
  const suburbPages: MetadataRoute.Sitemap = MELBOURNE_SUBURBS.map(
    (suburb) => ({
      url: `${baseUrl}/service-areas/${suburb}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    }),
  );

  // Service sub-pages (individual service detail pages)
  const serviceSubPages: MetadataRoute.Sitemap = SERVICE_SUB_PAGES.map(
    (path) => ({
      url: `${baseUrl}${path}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.85,
    }),
  );

  // Brand pages
  const brandPages: MetadataRoute.Sitemap = BRANDS.map((brand) => ({
    url: `${baseUrl}/brands/${brand}`,
    lastModified: new Date(),
    changeFrequency: "monthly" as const,
    priority: 0.7,
  }));

  // Self-care main page + brand sub-pages
  const selfCarePages: MetadataRoute.Sitemap = [
    {
      url: `${baseUrl}/self-care`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.7,
    },
    ...SELF_CARE_BRANDS.map((brand) => ({
      url: `${baseUrl}/self-care/${brand}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.6,
    })),
  ];

  return [
    ...staticPages,
    ...servicePages,
    ...serviceSubPages,
    ...suburbPages,
    ...brandPages,
    ...selfCarePages,
  ];
}

/*
SITEMAP STRUCTURE:
1. Static pages (priority 0.7-1.0): home, about, contact, services, service-areas, brands, blog
2. Service pages (priority 0.9): 6 main service pages
3. Service sub-pages (priority 0.85): 21 sub-pages
4. Dynamic suburb pages (priority 0.8): 247 suburbs
5. Brand pages (priority 0.7): 20 brands
6. Self-care pages (priority 0.6-0.7): 1 main + 19 brand sub-pages

This structure ensures:
✅ Search engines crawl all important pages
✅ Proper priority for revenue-generating pages
✅ Regional targeting for local SEO
✅ Efficient crawl budget usage
*/
